fix: creating ios dir before create a Localizable.xcstrings
The python scritp wans't localizing ios/Localizable.xcstrings because the script was not creating the directory before use
```with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/repos/Open/padawan-wallet/localization/scripts/../ios/Localizable.xcstrings```